In [2]:
import torch
torch.__version__

'2.9.1'

In [4]:
epi= torch.tensor(7)
epi.ndim

0

In [5]:
epi

tensor(7)

In [6]:
piss= epi.item()
piss

7

In [7]:
cake = torch.tensor([2,2])
 
print(cake.ndim)
print(cake.shape)

1
torch.Size([2])


In [8]:
coke= torch.tensor([[9,9],[2,3]])
print(coke.ndim)
print(coke.shape)

2
torch.Size([2, 2])


In [9]:
pepsi= torch.tensor([[[1,3,4],[4,5,6],[7,8,9]]])
print(pepsi.ndim)
print(pepsi.shape)

3
torch.Size([1, 3, 3])


In [10]:
sister= torch.rand(size=(3,255,255))
sister, sister.dtype, sister.shape

(tensor([[[0.5511, 0.0997, 0.7957,  ..., 0.7918, 0.9404, 0.4548],
          [0.1777, 0.0740, 0.8230,  ..., 0.8393, 0.1575, 0.0453],
          [0.4786, 0.9595, 0.7233,  ..., 0.7161, 0.3476, 0.6523],
          ...,
          [0.8835, 0.6579, 0.6880,  ..., 0.2220, 0.5645, 0.8524],
          [0.4218, 0.9748, 0.8722,  ..., 0.3937, 0.4636, 0.5330],
          [0.9552, 0.8429, 0.9084,  ..., 0.9254, 0.5464, 0.9111]],
 
         [[0.3602, 0.4369, 0.7800,  ..., 0.4180, 0.4191, 0.2976],
          [0.5303, 0.0266, 0.2519,  ..., 0.7790, 0.4441, 0.9497],
          [0.0708, 0.9226, 0.1198,  ..., 0.8475, 0.4249, 0.4270],
          ...,
          [0.2515, 0.0972, 0.6613,  ..., 0.1863, 0.3785, 0.7723],
          [0.3224, 0.1841, 0.6554,  ..., 0.4069, 0.0789, 0.0976],
          [0.7506, 0.7394, 0.7302,  ..., 0.4209, 0.8747, 0.5677]],
 
         [[0.3519, 0.4527, 0.7706,  ..., 0.1077, 0.9387, 0.5965],
          [0.2385, 0.7694, 0.7346,  ..., 0.6036, 0.7303, 0.6586],
          [0.4658, 0.2933, 0.6675,  ...,

In [11]:
ranger= torch.arange(1,10,2)
ranger

tensor([1, 3, 5, 7, 9])

In [12]:
torch.range(1,10)

/var/folders/45/v59x5szn4xzgx11gwjr0s8dh0000gn/T/ipykernel_2237/1136815087.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0867, 0.0859, 0.6425, 0.8625],
        [0.3491, 0.9735, 0.6248, 0.9939],
        [0.7537, 0.2639, 0.5984, 0.8587]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [14]:
qqq= torch.tensor([1,5,10])
qqq+10,qqq*10,qqq-10,qqq/10, qqq*qqq

(tensor([11, 15, 20]),
 tensor([ 10,  50, 100]),
 tensor([-9, -5,  0]),
 tensor([0.1000, 0.5000, 1.0000]),
 tensor([  1,  25, 100]))

In [15]:
torch.matmul(qqq,qqq), qqq@qqq

(tensor(126), tensor(126))

In [16]:
%%time
torch.matmul(qqq,qqq)

CPU times: user 223 μs, sys: 60 μs, total: 283 μs
Wall time: 249 μs


tensor(126)

In [17]:
%%time
qqq@qqq

CPU times: user 167 μs, sys: 56 μs, total: 223 μs
Wall time: 192 μs


tensor(126)

In [18]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(qqq)):
  value += qqq[i] * qqq[i]
value

CPU times: user 879 μs, sys: 1.88 ms, total: 2.76 ms
Wall time: 2.02 ms


tensor(126)

In [26]:
lol= torch.tensor([[1,2],[3,4],[5,6]],dtype= torch.float32)
print(lol.ndim)
print(lol.shape)

2
torch.Size([3, 2])


In [32]:
torch.manual_seed(42)
linear= torch.nn.Linear(in_features=2,out_features=6)
x= lol
output= linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [43]:
%%time
plati= torch.arange(1,100,10)
print(plati)
print(plati.min())
print(plati.max())
print(plati.type(torch.float32).mean())
print(plati.sum())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(1)
tensor(91)
tensor(46.)
tensor(460)
CPU times: user 2.15 ms, sys: 5.06 ms, total: 7.21 ms
Wall time: 4.55 ms


In [44]:
%%time
plati= torch.arange(1,100,10)
print(plati)
print(plati.min())
print(plati.max())

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(1)
tensor(91)
CPU times: user 1.53 ms, sys: 1e+03 μs, total: 2.53 ms
Wall time: 1.75 ms


In [46]:
%%time
plati= torch.arange(1,100,10)
print(torch.max(plati))
print(torch.min(plati))


tensor(91)
tensor(1)
CPU times: user 1.28 ms, sys: 1.15 ms, total: 2.43 ms
Wall time: 1.26 ms


In [72]:
%%time
ioop= torch.arange(1.,10.)
de=ioop.reshape(1,9)
de_stack= torch.stack([de,de,de],dim=0)
print(de_stack)
print(de_stack.shape)

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],

        [[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])
torch.Size([3, 1, 9])
CPU times: user 1.88 ms, sys: 1.3 ms, total: 3.17 ms
Wall time: 2 ms


In [76]:
orange= de.squeeze()
orange.shape

torch.Size([9])

In [81]:
img= torch.rand(3,255,255)
print(img)
pr= img.permute(1,0,2)
print(pr.shape)

tensor([[[0.3723, 0.1214, 0.0708,  ..., 0.5490, 0.2428, 0.1894],
         [0.1349, 0.5341, 0.0309,  ..., 0.6800, 0.5545, 0.9511],
         [0.2757, 0.7465, 0.9078,  ..., 0.6236, 0.4185, 0.8800],
         ...,
         [0.0566, 0.1159, 0.1132,  ..., 0.7648, 0.7136, 0.3229],
         [0.8087, 0.2501, 0.8905,  ..., 0.2136, 0.2366, 0.5892],
         [0.8634, 0.3408, 0.0800,  ..., 0.8126, 0.7566, 0.9232]],

        [[0.6810, 0.8964, 0.0678,  ..., 0.5324, 0.2890, 0.2351],
         [0.7045, 0.3127, 0.0634,  ..., 0.4874, 0.5013, 0.6102],
         [0.7357, 0.5354, 0.1139,  ..., 0.9591, 0.4785, 0.8835],
         ...,
         [0.4735, 0.2119, 0.0564,  ..., 0.8906, 0.5711, 0.8504],
         [0.3560, 0.7519, 0.5068,  ..., 0.5160, 0.2168, 0.4739],
         [0.6721, 0.9544, 0.7069,  ..., 0.8733, 0.2374, 0.5324]],

        [[0.6765, 0.6930, 0.2039,  ..., 0.3869, 0.2100, 0.8872],
         [0.2277, 0.6377, 0.9721,  ..., 0.3990, 0.1015, 0.2239],
         [0.1737, 0.2238, 0.2138,  ..., 0.0484, 0.6419, 0.

In [21]:
pop = torch.arange(1,10,1)
print(pop.shape)
eee= torch.arange(1,10,1).reshape(1,3,3)
print(eee.shape)

torch.Size([9])
torch.Size([1, 3, 3])


In [15]:
print(eee[0])
print(eee[0][0])
print(eee[0][0][0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [22]:
import numpy as np


In [27]:
yash= np.arange(1,10)
print(yash)
yash= torch.from_numpy(yash)
print(yash)
poppo= yash.numpy()
print(poppo)

[1 2 3 4 5 6 7 8 9]
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
[1 2 3 4 5 6 7 8 9]


In [28]:
import random

In [33]:
RANDOM_SEED=69
torch.manual_seed(seed= RANDOM_SEED)
popo= torch.rand(3,4)
torch.random.manual_seed(seed= RANDOM_SEED)
pepe=torch.rand(3,4)
popo==pepe

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [35]:
torch.backends.mps.is_available()

True

In [36]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [39]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device  #honestly seems like good practice to check out everything

'mps'

In [43]:
lop= torch.tensor([1,2,3])
print(lop,lop.device)
lop_gpu = lop.to(device)
print(lop_gpu,lop_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='mps:0') mps:0


In [44]:
lop_back_cpu= lop_gpu.cpu().numpy()
lop_back_cpu

array([1, 2, 3])